//! Core request / response / state types for the local-LLM service.

use crate::guard::Verdict;
use crate::mode::Mode;
use oxidemx_shared::config::SamplingConfig;
use serde::{Deserialize, Serialize};

// ── Message ───────────────────────────────────────────────────────────────────

/// Conversation participant role.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// Instructions from the operator / system.
    System,
    /// Turn from the human user.
    User,
    /// Turn generated by the assistant model.
    Assistant,
    /// Result returned from a tool call.
    Tool,
}

/// A single turn in a conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Who produced this message.
    pub role: Role,
    /// Text content of the message.
    pub content: String,
}

// ── ChatRequest ───────────────────────────────────────────────────────────────

/// A complete request sent to the local-LLM service.
#[derive(Debug, Clone)]
pub struct ChatRequest {
    /// Prior conversation turns (system + user + assistant history).
    pub messages: Vec<Message>,
    /// Routing / guard mode.
    pub mode: Mode,
    /// Tool definitions forwarded to the model (empty for non-tool-use modes).
    pub tools: Vec<serde_json::Value>,
    /// Per-request sampling override; `None` → use `mode.sampling()`.
    pub sampling_override: Option<SamplingConfig>,
    /// Optional system-prompt template injected before the messages.
    pub system_template: Option<String>,
}

// ── Usage ─────────────────────────────────────────────────────────────────────

/// Token-usage accounting returned with every response.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Usage {
    /// Tokens consumed by the prompt (input).
    pub prompt_tokens: u32,
    /// Tokens generated by the model (output).
    pub completion_tokens: u32,
}

// ── ChatResponse ──────────────────────────────────────────────────────────────

/// The model's response plus accounting and guard verdict.
#[derive(Debug, Clone)]
pub struct ChatResponse {
    /// Raw text generated by the model.
    pub text: String,
    /// Token usage for this turn.
    pub usage: Usage,
    /// Guard evaluation result.
    pub verdict: Verdict,
}

// ── ModelState / ModelStatusInfo ──────────────────────────────────────────────

/// Lifecycle state of a registered model.
///
/// Named `Failed { reason }` (not `Error`) to make clear this is a state, not
/// an error value — errors are signalled via [`crate::error::LocalError`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ModelState {
    /// Weights not yet loaded into memory.
    Unloaded,
    /// Weights are being downloaded or initialised.
    Loading,
    /// Model is loaded and ready to accept requests.
    Ready,
    /// Model is currently handling a request.
    Busy,
    /// The model encountered an unrecoverable error during load or inference.
    Failed {
        /// Description of the failure.
        reason: String,
    },
}

/// A snapshot of one registered model's runtime state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelStatusInfo {
    /// Short human-readable alias (matches [`oxidemx_shared::config::ModelSpec::alias`]).
    pub alias: String,
    /// Current lifecycle state.
    pub state: ModelState,
    /// Unix timestamp (seconds) of the last successful inference, or `None`
    /// if the model has never been used.
    pub last_used: Option<u64>,
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn model_state_is_a_state_not_an_error() {
        let s = ModelState::Failed { reason: "oom".into() };
        assert!(matches!(s, ModelState::Failed { .. }));
    }
}
