use crate::action::ActionKind;
use crate::animation::AnimationConfig;
use crate::buttons::ButtonsConfig;
use crate::conditions::Condition;
use crate::haptics::HapticsConfig;
use crate::pointer::{PointerConfig, ScrollConfig};
use crate::theme::ThemeName;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// One radial slice. Position in the parent vec determines its angular
/// placement (8 slices = 45° each, slot 0 = top, clockwise).
///
/// Fields beyond label / type / command / color / icon are optional so
/// older config.json files (which don't have submenu support yet) still
/// deserialize cleanly.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Slice {
    /// Stable id for the slice. Optional — generated by the editor when
    /// missing. Used to attach hover analytics, per-app overrides, etc.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_id: Option<String>,

    pub label: String,

    #[serde(rename = "type", default)]
    pub kind: ActionKind,

    /// Shell command for `Exec`, macro id for `Macro`, host index ("0".."2")
    /// for `EasySwitch`, ignored for other kinds.
    #[serde(default)]
    pub command: String,

    /// Slice highlight colour. The string is a key into the active theme's
    /// palette (e.g. "green", "sapphire", "teal"); the overlay resolves it
    /// to a concrete RGBA at render time.
    #[serde(default)]
    pub color: String,

    /// freedesktop symbolic icon name (preferred), an absolute path to a
    /// custom SVG/PNG, or one of the legacy internal ids handled by the
    /// hand-drawn renderer.
    #[serde(default)]
    pub icon: String,

    /// When true, render the icon at its original colours instead of
    /// tinting it to the slice colour. Useful for full-colour app
    /// icons (Firefox, Chromium, GIMP, …) where the brand identity
    /// matters; symbolic icons should leave this `false` so they
    /// pick up the slice colour as a monochrome highlight.
    #[serde(default, skip_serializing_if = "is_false")]
    pub icon_untinted: bool,

    /// Sub-items shown when this slice is hovered with `kind = Submenu`.
    /// Empty for non-submenu slices.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub submenu: Vec<Slice>,

    /// Optional visibility predicate. Slices whose predicate evaluates
    /// to `false` are skipped at render time — their slot stays empty
    /// rather than being filled by the next slice (so the menu's
    /// muscle-memory layout is preserved). `None` means always
    /// visible. See the `conditions` module for the variants.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visible_if: Option<Condition>,
}

/// One page of a multi-page radial menu — a named slice list with
/// optional app-context targeting. The menu always has at least one
/// page (the default global page); users can add more for
/// app-specific workflows that auto-activate when the menu opens
/// with a matching focused window, and/or extra global pages
/// reachable via the scroll-wheel cycle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RadialPage {
    /// Display name shown in the settings page picker and hover-tip
    /// over the page indicator dots in the overlay.
    pub name: String,

    #[serde(default)]
    pub slices: Vec<Slice>,

    /// Window classes (WM_CLASS / xdg-toplevel app_id) that
    /// auto-select this page when the menu opens with one of them
    /// focused. Empty = global page (always available, default
    /// active when no app-specific page matches).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub app_classes: Vec<String>,

    /// Whether this page participates in the scroll-wheel cycle.
    /// Implicitly true for global pages (empty `app_classes`); for
    /// app-context pages, set false to make the page only reachable
    /// through app focus (not via scroll cycling from another page).
    #[serde(default = "default_include_in_scroll")]
    pub include_in_scroll: bool,
}

fn default_include_in_scroll() -> bool {
    true
}

impl Default for RadialPage {
    fn default() -> Self {
        RadialPage {
            name: "Default".into(),
            slices: Vec::new(),
            app_classes: Vec::new(),
            include_in_scroll: true,
        }
    }
}

/// Visual knobs the user controls directly from the settings UI.
/// These don't animate — they're the "this is how I want it to
/// look at rest" multipliers applied on top of the theme palette.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisualSettings {
    /// Multiplier on the wheel disc + halo background alpha. 1.0 =
    /// full theme opacity, 0.0 = invisible disc (you'd still see
    /// the slices). Caps at 1.0; negatives are clamped at 0.
    #[serde(default = "default_menu_bg_opacity")]
    pub menu_background_opacity: f32,

    /// Multiplier on the per-slice hover highlight peak. 1.0 = full
    /// hover glow (today's default), 0.0 = no highlight at all.
    /// Useful for users who find the hover flash too loud.
    #[serde(default = "default_slice_highlight_opacity")]
    pub slice_highlight_opacity: f32,

    /// Font size (px) for the centre-puck label that shows the
    /// currently-hovered slice's name. 0 disables the label
    /// entirely; sensible range ~10-20.
    #[serde(default = "default_center_label_size")]
    pub center_label_size: f32,

    /// Optional font family override for the centre label and
    /// (future) other rendered text. Empty = iced's default
    /// system font.
    #[serde(default)]
    pub font_family: String,
}

/// Helper for `#[serde(skip_serializing_if = ...)]` on the
/// `icon_untinted` flag — keeps default-`false` slices off-disk
/// so the JSON stays minimal.
fn is_false(b: &bool) -> bool {
    !b
}

fn default_menu_bg_opacity() -> f32 {
    1.0
}
fn default_slice_highlight_opacity() -> f32 {
    1.0
}
fn default_center_label_size() -> f32 {
    13.0
}

impl Default for VisualSettings {
    fn default() -> Self {
        VisualSettings {
            menu_background_opacity: default_menu_bg_opacity(),
            slice_highlight_opacity: default_slice_highlight_opacity(),
            center_label_size: default_center_label_size(),
            font_family: String::new(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct RadialMenuConfig {
    /// Legacy single-page slice list. Pre-multipage configs only
    /// have this. Loaders should call [`Self::normalize_pages`] —
    /// it lifts these into `pages[0]` and clears the field so
    /// downstream code only reads from `pages`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub slices: Vec<Slice>,

    /// Multi-page menu. Page 0 is the default page (always
    /// reachable via the scroll cycle). Additional pages are either
    /// extra global pages or app-context pages that auto-select on
    /// focus. After [`Self::normalize_pages`] runs, this is
    /// guaranteed to contain at least one page.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub pages: Vec<RadialPage>,

    /// Replaces the configured slot 5 (Emoji) with an Easy-Switch submenu
    /// when true. Mirrors the existing daemon behaviour.
    #[serde(default)]
    pub easy_switch_shortcuts: bool,

    /// OS labels for each Easy-Switch host slot (length 3). Used to pick
    /// the host icon in the Easy-Switch submenu.
    #[serde(default)]
    pub easy_switch_host_os: Vec<String>,

    /// Per-element animation tweaks. Optional — when missing, every
    /// element falls back to its `ElementAnimation::*_default()`
    /// preset. Inotify-reloaded so users iterate live.
    #[serde(default)]
    pub animation: AnimationConfig,

    /// Static visual knobs (background opacity, highlight intensity)
    /// the user controls directly from the settings UI.
    #[serde(default)]
    pub visuals: VisualSettings,
}

impl RadialMenuConfig {
    /// Migrate legacy `slices` (pre-multipage configs) into
    /// `pages[0]` and ensure at least one page exists. Idempotent;
    /// safe to call on already-migrated configs. Run after every
    /// load/parse so the rest of the codebase only has to read
    /// from `pages`.
    pub fn normalize_pages(&mut self) {
        if !self.slices.is_empty() {
            let legacy = std::mem::take(&mut self.slices);
            if self.pages.is_empty() {
                self.pages.push(RadialPage {
                    name: "Default".into(),
                    slices: legacy,
                    app_classes: Vec::new(),
                    include_in_scroll: true,
                });
            } else if self.pages[0].slices.is_empty() {
                // Tolerate a config that has both fields populated by
                // hand: prefer pages[0] if it has slices, otherwise
                // backfill from the legacy field.
                self.pages[0].slices = legacy;
            }
        }
        if self.pages.is_empty() {
            self.pages.push(RadialPage::default());
        }
    }

    /// Indices of the pages that participate in the scroll-wheel
    /// cycle. A global page (empty `app_classes`) is always in the
    /// cycle; an app-context page is in the cycle only when
    /// `include_in_scroll` is true.
    pub fn cycle_pages(&self) -> Vec<usize> {
        self.pages
            .iter()
            .enumerate()
            .filter(|(_, p)| p.app_classes.is_empty() || p.include_in_scroll)
            .map(|(i, _)| i)
            .collect()
    }

    /// Page index to activate when the menu opens with the given
    /// focused window class. First page whose `app_classes`
    /// contains the class (case-insensitive); falls back to 0.
    pub fn page_for_class(&self, class: Option<&str>) -> usize {
        let class = match class {
            Some(c) if !c.is_empty() => c,
            _ => return 0,
        };
        let lc = class.to_lowercase();
        self.pages
            .iter()
            .position(|p| p.app_classes.iter().any(|c| c.to_lowercase() == lc))
            .unwrap_or(0)
    }

    /// Read access to the slices of a specific page index, with
    /// graceful fallback to an empty slice if the index is out of
    /// range — guards against a stale active-page index after a
    /// page is deleted.
    pub fn slices_of(&self, page_idx: usize) -> &[Slice] {
        self.pages
            .get(page_idx)
            .map(|p| p.slices.as_slice())
            .unwrap_or(&[])
    }

    /// Convenience: slices of page 0 (the default page). Used by
    /// callers that don't yet support multi-page navigation —
    /// daemon HID++ button mapping, the dump_menu example, etc.
    pub fn default_slices(&self) -> &[Slice] {
        self.slices_of(0)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AppConfig {
    #[serde(default)]
    pub theme: ThemeName,

    #[serde(default)]
    pub radial_menu: RadialMenuConfig,

    /// Per-event haptic feedback patterns + debounce timings.
    /// Optional in the JSON; missing = sensible defaults from
    /// `HapticsConfig::default()`.
    #[serde(default)]
    pub haptics: HapticsConfig,

    /// Pointer speed + acceleration (Point & Scroll tab → Pointer).
    #[serde(default)]
    pub pointer: PointerConfig,

    /// Scroll wheel behaviour (Point & Scroll tab → Scroll).
    #[serde(default)]
    pub scroll: ScrollConfig,

    /// Per-button action assignments. Same on-disk shape as the
    /// daemon's `daemon::config::ButtonsConfig`.
    #[serde(default)]
    pub buttons: ButtonsConfig,

    /// Per-app menu profile names. When the focused window's WM_CLASS (or
    /// equivalent) matches a key here, the daemon points the overlay at
    /// `~/.config/juhradial/profiles/<value>.json` instead of the main
    /// config. Empty by default — no profile switching.
    #[serde(default, skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    pub app_profiles: std::collections::BTreeMap<String, String>,
}

/// Default location of the user's main config: `~/.config/juhradial/config.json`.
pub fn default_config_path() -> Option<PathBuf> {
    dirs_config_dir().map(|d| d.join("juhradial").join("config.json"))
}

/// Bundled starter config — written to `~/.config/juhradial/config.json`
/// the first time the overlay can't find one. Gives users a working
/// 8-slice menu on first run instead of an empty ring; they edit
/// from there in the settings UI (or by hand). Stored as raw JSON so
/// the file's schema is the single source of truth — no duplicated
/// Rust struct literal that would drift from the on-disk version.
pub const DEFAULT_CONFIG_JSON: &str = include_str!("../default-config.json");

/// Write the bundled starter config to `path` if no file exists
/// there yet. Returns `true` if the file was created (a fresh
/// seed), `false` if it already existed.
pub fn seed_default_config_if_missing(path: &Path) -> Result<bool, ConfigError> {
    if path.exists() {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(ConfigError::Io)?;
    }
    std::fs::write(path, DEFAULT_CONFIG_JSON).map_err(ConfigError::Io)?;
    Ok(true)
}

/// Directory holding per-app profile overrides (one JSON file per profile).
pub fn profiles_dir() -> Option<PathBuf> {
    dirs_config_dir().map(|d| d.join("juhradial").join("profiles"))
}

fn dirs_config_dir() -> Option<PathBuf> {
    // Avoid pulling in `dirs` at this level — keep juhradial-shared
    // dependency-free aside from serde so the daemon can use it without
    // adding any indirect deps. Mirror dirs::config_dir()'s logic.
    if let Some(xdg) = std::env::var_os("XDG_CONFIG_HOME") {
        let p = PathBuf::from(xdg);
        if p.is_absolute() {
            return Some(p);
        }
    }
    std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config"))
}

impl AppConfig {
    /// Load and parse a config file from disk. Returns the default config
    /// if the file is missing — the daemon writes a fresh one on first
    /// run.
    pub fn load_from(path: &Path) -> Result<Self, ConfigError> {
        let mut cfg = match std::fs::read_to_string(path) {
            Ok(s) => serde_json::from_str::<Self>(&s).map_err(ConfigError::Parse)?,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                let mut def = AppConfig::default();
                def.radial_menu.normalize_pages();
                return Ok(def);
            }
            Err(e) => return Err(ConfigError::Io(e)),
        };
        cfg.radial_menu.normalize_pages();
        Ok(cfg)
    }
}

#[derive(Debug)]
pub enum ConfigError {
    Io(std::io::Error),
    Parse(serde_json::Error),
}

impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConfigError::Io(e) => write!(f, "config I/O error: {e}"),
            ConfigError::Parse(e) => write!(f, "config parse error: {e}"),
        }
    }
}

impl std::error::Error for ConfigError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ConfigError::Io(e) => Some(e),
            ConfigError::Parse(e) => Some(e),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_minimal_config() {
        let json = r#"{
            "theme": "dracula",
            "radial_menu": {
                "slices": [
                    {"label": "Terminal", "type": "exec", "command": "ptyxis", "color": "green", "icon": "utilities-terminal-symbolic"}
                ]
            }
        }"#;
        let mut cfg: AppConfig = serde_json::from_str(json).unwrap();
        cfg.radial_menu.normalize_pages();
        assert_eq!(cfg.theme, ThemeName::Dracula);
        // Legacy slices migrated into pages[0].
        assert!(cfg.radial_menu.slices.is_empty());
        assert_eq!(cfg.radial_menu.pages.len(), 1);
        let page = &cfg.radial_menu.pages[0];
        assert_eq!(page.slices.len(), 1);
        let s = &page.slices[0];
        assert_eq!(s.label, "Terminal");
        assert_eq!(s.kind, ActionKind::Exec);
        assert_eq!(s.command, "ptyxis");
    }

    #[test]
    fn normalize_pages_is_idempotent() {
        let json = r#"{
            "radial_menu": {
                "pages": [
                    {"name": "Main", "slices": [
                        {"label": "A", "type": "exec", "command": "true"}
                    ]},
                    {"name": "Dev", "app_classes": ["code"], "include_in_scroll": false,
                     "slices": [{"label": "B", "type": "exec", "command": "true"}]}
                ]
            }
        }"#;
        let mut cfg: AppConfig = serde_json::from_str(json).unwrap();
        cfg.radial_menu.normalize_pages();
        cfg.radial_menu.normalize_pages();
        assert_eq!(cfg.radial_menu.pages.len(), 2);
        assert_eq!(cfg.radial_menu.cycle_pages(), vec![0]);
        assert_eq!(cfg.radial_menu.page_for_class(Some("code")), 1);
        assert_eq!(cfg.radial_menu.page_for_class(Some("Code")), 1);
        assert_eq!(cfg.radial_menu.page_for_class(Some("firefox")), 0);
        assert_eq!(cfg.radial_menu.page_for_class(None), 0);
    }

    #[test]
    fn unknown_theme_round_trips_as_custom() {
        let cfg: AppConfig = serde_json::from_str(r#"{"theme":"my-cool-theme"}"#).unwrap();
        assert_eq!(cfg.theme, ThemeName::Custom("my-cool-theme".into()));
        let back = serde_json::to_string(&cfg).unwrap();
        assert!(back.contains(r#""theme":"my-cool-theme""#));
    }
}
