use crate::action::ActionKind;
use crate::conditions::Condition;
use crate::theme::ThemeName;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// One radial slice. Position in the parent vec determines its angular
/// placement (8 slices = 45° each, slot 0 = top, clockwise).
///
/// Fields beyond label / type / command / color / icon are optional so
/// older config.json files (which don't have submenu support yet) still
/// deserialize cleanly.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Slice {
    /// Stable id for the slice. Optional — generated by the editor when
    /// missing. Used to attach hover analytics, per-app overrides, etc.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_id: Option<String>,

    pub label: String,

    #[serde(rename = "type", default)]
    pub kind: ActionKind,

    /// Shell command for `Exec`, macro id for `Macro`, host index ("0".."2")
    /// for `EasySwitch`, ignored for other kinds.
    #[serde(default)]
    pub command: String,

    /// Slice highlight colour. The string is a key into the active theme's
    /// palette (e.g. "green", "sapphire", "teal"); the overlay resolves it
    /// to a concrete RGBA at render time.
    #[serde(default)]
    pub color: String,

    /// freedesktop symbolic icon name (preferred), an absolute path to a
    /// custom SVG/PNG, or one of the legacy internal ids handled by the
    /// hand-drawn renderer.
    #[serde(default)]
    pub icon: String,

    /// Sub-items shown when this slice is hovered with `kind = Submenu`.
    /// Empty for non-submenu slices.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub submenu: Vec<Slice>,

    /// Optional visibility predicate. Slices whose predicate evaluates
    /// to `false` are skipped at render time — their slot stays empty
    /// rather than being filled by the next slice (so the menu's
    /// muscle-memory layout is preserved). `None` means always
    /// visible. See the `conditions` module for the variants.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visible_if: Option<Condition>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct RadialMenuConfig {
    #[serde(default)]
    pub slices: Vec<Slice>,

    /// Replaces the configured slot 5 (Emoji) with an Easy-Switch submenu
    /// when true. Mirrors the existing daemon behaviour.
    #[serde(default)]
    pub easy_switch_shortcuts: bool,

    /// OS labels for each Easy-Switch host slot (length 3). Used to pick
    /// the host icon in the Easy-Switch submenu.
    #[serde(default)]
    pub easy_switch_host_os: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AppConfig {
    #[serde(default)]
    pub theme: ThemeName,

    #[serde(default)]
    pub radial_menu: RadialMenuConfig,

    /// Per-app menu profile names. When the focused window's WM_CLASS (or
    /// equivalent) matches a key here, the daemon points the overlay at
    /// `~/.config/juhradial/profiles/<value>.json` instead of the main
    /// config. Empty by default — no profile switching.
    #[serde(default, skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    pub app_profiles: std::collections::BTreeMap<String, String>,
}

/// Default location of the user's main config: `~/.config/juhradial/config.json`.
pub fn default_config_path() -> Option<PathBuf> {
    dirs_config_dir().map(|d| d.join("juhradial").join("config.json"))
}

/// Directory holding per-app profile overrides (one JSON file per profile).
pub fn profiles_dir() -> Option<PathBuf> {
    dirs_config_dir().map(|d| d.join("juhradial").join("profiles"))
}

fn dirs_config_dir() -> Option<PathBuf> {
    // Avoid pulling in `dirs` at this level — keep juhradial-shared
    // dependency-free aside from serde so the daemon can use it without
    // adding any indirect deps. Mirror dirs::config_dir()'s logic.
    if let Some(xdg) = std::env::var_os("XDG_CONFIG_HOME") {
        let p = PathBuf::from(xdg);
        if p.is_absolute() {
            return Some(p);
        }
    }
    std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config"))
}

impl AppConfig {
    /// Load and parse a config file from disk. Returns the default config
    /// if the file is missing — the daemon writes a fresh one on first
    /// run.
    pub fn load_from(path: &Path) -> Result<Self, ConfigError> {
        match std::fs::read_to_string(path) {
            Ok(s) => serde_json::from_str(&s).map_err(ConfigError::Parse),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                Ok(AppConfig::default())
            }
            Err(e) => Err(ConfigError::Io(e)),
        }
    }
}

#[derive(Debug)]
pub enum ConfigError {
    Io(std::io::Error),
    Parse(serde_json::Error),
}

impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConfigError::Io(e) => write!(f, "config I/O error: {e}"),
            ConfigError::Parse(e) => write!(f, "config parse error: {e}"),
        }
    }
}

impl std::error::Error for ConfigError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ConfigError::Io(e) => Some(e),
            ConfigError::Parse(e) => Some(e),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_minimal_config() {
        let json = r#"{
            "theme": "dracula",
            "radial_menu": {
                "slices": [
                    {"label": "Terminal", "type": "exec", "command": "ptyxis", "color": "green", "icon": "utilities-terminal-symbolic"}
                ]
            }
        }"#;
        let cfg: AppConfig = serde_json::from_str(json).unwrap();
        assert_eq!(cfg.theme, ThemeName::Dracula);
        assert_eq!(cfg.radial_menu.slices.len(), 1);
        let s = &cfg.radial_menu.slices[0];
        assert_eq!(s.label, "Terminal");
        assert_eq!(s.kind, ActionKind::Exec);
        assert_eq!(s.command, "ptyxis");
    }

    #[test]
    fn unknown_theme_round_trips_as_custom() {
        let cfg: AppConfig = serde_json::from_str(r#"{"theme":"my-cool-theme"}"#).unwrap();
        assert_eq!(cfg.theme, ThemeName::Custom("my-cool-theme".into()));
        let back = serde_json::to_string(&cfg).unwrap();
        assert!(back.contains(r#""theme":"my-cool-theme""#));
    }
}
