use crate::action::ActionKind;
use crate::animation::AnimationConfig;
use crate::buttons::ButtonsConfig;
use crate::conditions::Condition;
use crate::gaming::GamingConfig;
use crate::haptics::HapticsConfig;
use crate::pointer::{PointerConfig, ScrollConfig};
use crate::theme::ThemeName;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// One radial slice. Position in the parent vec determines its angular
/// placement (8 slices = 45° each, slot 0 = top, clockwise).
///
/// Fields beyond label / type / command / color / icon are optional so
/// older config.json files (which don't have submenu support yet) still
/// deserialize cleanly.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Slice {
    /// Stable id for the slice. Optional — generated by the editor when
    /// missing. Used to attach hover analytics, per-app overrides, etc.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_id: Option<String>,

    pub label: String,

    #[serde(rename = "type", default)]
    pub kind: ActionKind,

    /// Shell command for `Exec`, macro id for `Macro`, host index ("0".."2")
    /// for `EasySwitch`, ignored for other kinds.
    #[serde(default)]
    pub command: String,

    /// Slice highlight colour. The string is a key into the active theme's
    /// palette (e.g. "green", "sapphire", "teal"); the overlay resolves it
    /// to a concrete RGBA at render time.
    #[serde(default)]
    pub color: String,

    /// freedesktop symbolic icon name (preferred), an absolute path to a
    /// custom SVG/PNG, or one of the legacy internal ids handled by the
    /// hand-drawn renderer.
    #[serde(default)]
    pub icon: String,

    /// When true, render the icon at its original colours instead of
    /// tinting it to the slice colour. Useful for full-colour app
    /// icons (Firefox, Chromium, GIMP, …) where the brand identity
    /// matters; symbolic icons should leave this `false` so they
    /// pick up the slice colour as a monochrome highlight.
    #[serde(default, skip_serializing_if = "is_false")]
    pub icon_untinted: bool,

    /// Optional longer-form notes / tooltip text for the slice.
    /// Renders as a smaller subtitle under the slice label inside
    /// the overlay's centre puck while the slice is hovered — use
    /// it for "deploy to staging via shipit (don't run on prod!)"
    /// type reminders. Empty string = no subtitle (the puck just
    /// shows the label, same as before this field existed).
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub description: String,

    /// Sub-items shown when this slice is hovered with `kind = Submenu`.
    /// Empty for non-submenu slices.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub submenu: Vec<Slice>,

    /// Optional visibility predicate. Slices whose predicate evaluates
    /// to `false` are skipped at render time — their slot stays empty
    /// rather than being filled by the next slice (so the menu's
    /// muscle-memory layout is preserved). `None` means always
    /// visible. See the `conditions` module for the variants.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visible_if: Option<Condition>,

    /// Live-data binding for `ActionKind::Widget` slices. `None` on
    /// every other kind (and on widget slices hand-edited without a
    /// source — those render the stub placeholder).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub widget: Option<WidgetConfig>,

    /// Adjustment target for `ActionKind::Dial` slices. `None` on
    /// every other kind.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dial: Option<DialKind>,
}

/// Data binding for a live widget wedge (Splice Widgets page).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WidgetConfig {
    pub source: WidgetSource,
    /// Optional format override for the big value (e.g. "{}%").
    /// `None` = the source's default formatting.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
}

/// Which live data feed a widget wedge renders.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WidgetSource {
    Weather,
    Cpu,
    Memory,
    Network,
    Disk,
    TasksDue,
    MouseBattery,
}

/// What an `ActionKind::Dial` slice adjusts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DialKind {
    Brightness,
    Volume,
}

/// One page of a multi-page radial menu — a named slice list with
/// optional app-context targeting. The menu always has at least one
/// page (the default global page); users can add more for
/// app-specific workflows that auto-activate when the menu opens
/// with a matching focused window, and/or extra global pages
/// reachable via the scroll-wheel cycle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RadialPage {
    /// Display name shown in the settings page picker and hover-tip
    /// over the page indicator dots in the overlay.
    pub name: String,

    #[serde(default)]
    pub slices: Vec<Slice>,

    /// Window classes (WM_CLASS / xdg-toplevel app_id) that
    /// auto-select this page when the menu opens with one of them
    /// focused. Empty = global page (always available, default
    /// active when no app-specific page matches).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub app_classes: Vec<String>,

    /// Whether this page participates in the scroll-wheel cycle.
    /// Implicitly true for global pages (empty `app_classes`); for
    /// app-context pages, set false to make the page only reachable
    /// through app focus (not via scroll cycling from another page).
    #[serde(default = "default_include_in_scroll")]
    pub include_in_scroll: bool,

    /// How many wedges this page renders. Clamped to 2..=8 by the
    /// overlay; smaller counts give bigger easier-to-hit slices,
    /// 8 (the default) is the dense layout most users expect.
    /// Per-page so a "quick actions" page can be a 4-slot ring
    /// while a "full launcher" page stays at 8.
    #[serde(default = "default_slot_count")]
    pub slot_count: u8,
}

fn default_include_in_scroll() -> bool {
    true
}

fn default_slot_count() -> u8 {
    8
}

impl Default for RadialPage {
    fn default() -> Self {
        RadialPage {
            name: "Default".into(),
            slices: Vec::new(),
            app_classes: Vec::new(),
            include_in_scroll: true,
            slot_count: default_slot_count(),
        }
    }
}

impl RadialPage {
    /// Resolve the page's slot count, clamped to the overlay's
    /// supported range (2..=8). Use this everywhere that reads
    /// `slot_count` so a malformed config (0, 99, …) can't render
    /// undefined geometry.
    pub fn effective_slot_count(&self) -> u8 {
        self.slot_count.clamp(2, 8)
    }
}

/// Visual knobs the user controls directly from the settings UI.
/// These don't animate — they're the "this is how I want it to
/// look at rest" multipliers applied on top of the theme palette.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VisualSettings {
    /// Multiplier on the wheel disc + halo background alpha. 1.0 =
    /// full theme opacity, 0.0 = invisible disc (you'd still see
    /// the slices). Caps at 1.0; negatives are clamped at 0.
    #[serde(default = "default_menu_bg_opacity")]
    pub menu_background_opacity: f32,

    /// Multiplier on the per-slice hover highlight peak. 1.0 = full
    /// hover glow (today's default), 0.0 = no highlight at all.
    /// Useful for users who find the hover flash too loud.
    #[serde(default = "default_slice_highlight_opacity")]
    pub slice_highlight_opacity: f32,

    /// Font size (px) for the centre-puck label that shows the
    /// currently-hovered slice's name. 0 disables the label
    /// entirely; sensible range ~10-20.
    #[serde(default = "default_center_label_size")]
    pub center_label_size: f32,

    /// Optional font family override for the centre label and
    /// (future) other rendered text. Empty = iced's default
    /// system font.
    #[serde(default)]
    pub font_family: String,

    /// How long the user must dwell on a slice before its
    /// description tooltip appears, in milliseconds. 0 disables
    /// the delay (instant tooltip), `u32::MAX`/large values
    /// effectively disable the tooltip. Sensible range 200-1500.
    #[serde(default = "default_tooltip_delay_ms")]
    pub tooltip_delay_ms: u32,

    /// Font size for the arced tooltip text. 0 hides the tooltip
    /// entirely (icon-only ring).
    #[serde(default = "default_tooltip_font_size")]
    pub tooltip_font_size: f32,

    /// When `true`, the tooltip ignores `tooltip_font_family` and
    /// uses iced's bundled monospace. Monospace makes per-glyph
    /// arc spacing exact (every cell is the same width), at the
    /// cost of looking more "technical". Default true because
    /// proportional fonts on a curved arc tend to bunch.
    #[serde(default = "default_tooltip_use_monospace")]
    pub tooltip_use_monospace: bool,

    /// Optional font family for the arced tooltip (only used when
    /// `tooltip_use_monospace` is `false`). Empty = inherit
    /// `font_family`. Family must be installed on the system.
    #[serde(default)]
    pub tooltip_font_family: String,

    /// Palette colour key used for the tooltip's background
    /// ribbon. One of the surface keys: `crust`, `mantle`,
    /// `base`, `surface0`, `surface1`, `surface2`, `overlay0`,
    /// `overlay1`. Defaults to `crust` (darkest), which gives the
    /// most contrast against light text.
    #[serde(default = "default_tooltip_bg_color")]
    pub tooltip_bg_color: String,

    /// Background ribbon alpha, 0..1. 0 hides the ribbon entirely
    /// (text on transparent), 1 = fully opaque colour. Default
    /// 0.85 leaves a hair of show-through.
    #[serde(default = "default_tooltip_bg_alpha")]
    pub tooltip_bg_alpha: f32,

    /// Palette colour key used for the tooltip text. One of:
    /// `text`, `subtext1`, `subtext0`, `accent`. Defaults to
    /// `text` (highest-contrast option in any theme).
    #[serde(default = "default_tooltip_text_color")]
    pub tooltip_text_color: String,

    /// Intensity of the aurora backdrop shader (0..=1). 0 hides
    /// the effect entirely (no GPU work). Drives a per-frame
    /// fragment shader that paints a slow conic gradient between
    /// the active theme's accents behind the menu — purely
    /// decorative, runs only when the menu is open.
    #[serde(default = "default_aurora_intensity")]
    pub aurora_intensity: f32,

    /// Intensity of the haptic-ripple shader (0..=1). 0 disables
    /// — no shader pass runs on haptic events. > 0 paints a
    /// thin expanding ring from menu centre every time a haptic
    /// event fires (menu_appear, slice_change, page_change,
    /// confirm, etc.) — visual feedback synced to the physical
    /// motor pulse.
    #[serde(default = "default_ripple_intensity")]
    pub ripple_intensity: f32,

    /// Intensity of the SDF hover-glow shader (0..=1). 0
    /// disables. Replaces the canvas-side hover wash with a
    /// resolution-independent glow that follows the wedge
    /// boundary and uses the active accent colour. Coloured
    /// outline + soft outer aura that scales with the highlight
    /// tween.
    #[serde(default = "default_hover_glow_intensity")]
    pub hover_glow_intensity: f32,

    /// Intensity of the dispatch-burst shader (0..=1). 0
    /// disables. Renders a one-shot burst from the activated
    /// slice when an action fires (confirm haptic). Style picks
    /// between sparks / shockwave / glow looks.
    #[serde(default = "default_dispatch_burst_intensity")]
    pub dispatch_burst_intensity: f32,

    /// Visual style of the dispatch-burst shader. See
    /// [`DispatchBurstStyle`] for variants.
    #[serde(default = "default_dispatch_burst_style")]
    pub dispatch_burst_style: DispatchBurstStyle,

    /// Intensity of the SDF wedge-ring shader (0..=1). 0
    /// disables — canvas paints wedges as historically. > 0
    /// fades the canvas-side wedge fills out and lets the SDF
    /// layer paint them instead. Spike feature; defaults to off
    /// while the look is being validated.
    #[serde(default = "default_sdf_ring_intensity")]
    pub sdf_ring_intensity: f32,

    /// Intensity of the parallax-tilt shader (0..=1). 0 disables
    /// the effect entirely (no GPU work). When > 0, the hovered
    /// slice gets a directional specular highlight + soft inset
    /// shadow that tracks the cursor — cheap visual analogue of
    /// "the slice is tilting toward your finger". Pairs well
    /// with `hover_glow` (different visual layer; tilt is
    /// inside-the-wedge, glow is along-the-edge).
    #[serde(default = "default_hover_tilt_intensity")]
    pub hover_tilt_intensity: f32,

    /// How much the parallax-tilt shader darkens the side of the
    /// wedge facing AWAY from the cursor (0..=1). 0 = no shadow
    /// (only highlight); 1 = strong inset shadow opposite the
    /// cursor. Default 0.5 reads as a "leaned" surface without
    /// looking blown out.
    #[serde(default = "default_hover_tilt_shadow")]
    pub hover_tilt_shadow: f32,

    /// Specular highlight tightness for the parallax-tilt shader
    /// (0..=1). Higher = smaller, sharper highlight; lower =
    /// broader wash. 0.5 is the visual sweet spot for an MX-Master-
    /// sized menu.
    #[serde(default = "default_hover_tilt_sharpness")]
    pub hover_tilt_sharpness: f32,

    /// Intensity of the disc-bevel shader (0..=1). 0 disables —
    /// no GPU work. > 0 paints a directional rim light along the
    /// outer edge + a carved inset shadow at the inner ring,
    /// framing the menu in 3D regardless of hover.
    #[serde(default = "default_disc_bevel_intensity")]
    pub disc_bevel_intensity: f32,

    /// Intensity of the centre-dome shader (0..=1). 0 disables.
    /// > 0 turns the centre puck into a Phong-shaded sphere with
    /// > directional Lambert wash + tight specular highlight.
    #[serde(default = "default_center_dome_intensity")]
    pub center_dome_intensity: f32,

    /// Intensity of the slice-bevel shader (0..=1). 0 disables.
    /// > 0 paints carved grooves between every wedge with
    /// > directional rim lighting — each slice reads as its own
    /// > raised 3D button.
    #[serde(default = "default_slice_bevel_intensity")]
    pub slice_bevel_intensity: f32,

    /// Intensity of the drop-shadow shader (0..=1). 0 disables.
    /// > 0 paints a soft falloff shadow OUTSIDE the disc, offset
    /// > away from the light source. Reads as the menu casting a
    /// > real cast shadow onto whatever is behind it — turns the
    /// > ring from "painted on the screen" into a floating object.
    #[serde(default = "default_drop_shadow_intensity")]
    pub drop_shadow_intensity: f32,

    /// Intensity of the specular-sweep shader (0..=1). 0 disables.
    /// > 0 paints an animated narrow band of light that slowly
    /// > rotates around the disc rim — like a polished surface
    /// > catching ambient light. Lit-side gated so the sweep
    /// > fades out on the shadow hemisphere.
    #[serde(default = "default_specular_sweep_intensity")]
    pub specular_sweep_intensity: f32,

    /// Period in seconds for one full revolution of the
    /// specular sweep around the disc. Larger = slower, more
    /// meditative; smaller = faster, more energetic. Default 8s.
    #[serde(default = "default_specular_sweep_period_s")]
    pub specular_sweep_period_s: f32,

    /// Direction of the virtual light source for every 3D-framing
    /// shader (drop_shadow / disc_bevel / slice_bevel / center_
    /// dome / hover_tilt), in radians, canvas convention (slice 0
    /// at `-π/2` = top). Default `-3π/4` is upper-left, the
    /// universal "this is 3D" convention. Rotating this knob
    /// rotates the whole menu's lighting cohesively — highlights
    /// and shadows stay consistent across all shaders because
    /// they all read the same value.
    #[serde(default = "default_light_angle_rad")]
    pub light_angle_rad: f32,

    /// Display the page name briefly in the centre puck on a
    /// page swap (scroll-cycle, app-context auto-swap on open).
    /// `true` = visible flash; `false` = no flash. Hover labels
    /// always take precedence either way.
    #[serde(default = "default_page_name_show")]
    pub page_name_show: bool,

    /// How long the page name stays at FULL opacity after the
    /// slide-in completes, before starting its fade-out tail.
    /// Total on-screen time = `2 × transition_ms + visible_ms`.
    #[serde(default = "default_page_name_visible_ms")]
    pub page_name_visible_ms: u32,

    /// Duration of both the slide-in (with optional cross-slide
    /// of the previous page's name) AND the final fade-out.
    /// Same value used for both phases for visual symmetry.
    #[serde(default = "default_page_name_transition_ms")]
    pub page_name_transition_ms: u32,

    /// Horizontal slide distance in logical pixels. Forward
    /// cycles slide the new name in from `+slide_distance` and
    /// the old name out to `-slide_distance`; backward cycles
    /// flip both signs. `0` collapses to pure crossfade.
    #[serde(default = "default_page_name_slide_distance_px")]
    pub page_name_slide_distance_px: f32,

    /// Render the page-name flash as an arc lifted above the
    /// centre puck, instead of inside it. Keeps the label out
    /// of the cursor's path (since the cursor sits on the puck
    /// when scrolling to cycle pages) and echoes the menu's
    /// circular geometry. `false` renders the label flat and
    /// centred inside the puck (legacy look).
    #[serde(default = "default_page_name_arced")]
    pub page_name_arced: bool,

    /// Force monospace for the page name. The arced layout
    /// assigns each character a uniform angular slot — a
    /// proportional font produces uneven gaps (narrow glyphs
    /// look isolated, wide ones look cramped). Monospace makes
    /// every cell hold an equal-width glyph, fixing the
    /// spacing. Defaults `true`; turn off to use a proportional
    /// font for the flat layout (or to experiment with arced
    /// proportional rendering).
    #[serde(default = "default_page_name_use_monospace")]
    pub page_name_use_monospace: bool,

    /// Page-name-specific font family override. Empty string
    /// inherits `font_family`. Ignored when
    /// `page_name_use_monospace` is true (which forces the
    /// platform monospace family).
    #[serde(default)]
    pub page_name_font_family: String,
}

/// What the dispatch-burst shader looks like. Selectable from
/// the GPU shaders card in settings — each style is a different
/// fragment-shader branch in `dispatch_burst.wgsl`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum DispatchBurstStyle {
    /// Bright particles fly outward from the activated slice in
    /// scattered directions, fading as they expand. Reads as
    /// "this action sparked".
    #[default]
    Sparks,
    /// Multiple concentric rings expand from the activated
    /// slice's icon — more emphatic version of the haptic
    /// ripple, anchored at the slice rather than menu centre.
    Shockwave,
    /// Single bright flash centred on the activated slice that
    /// fades quickly. Subtle, fastest visual feedback.
    Glow,
}

/// Helper for `#[serde(skip_serializing_if = ...)]` on the
/// `icon_untinted` flag — keeps default-`false` slices off-disk
/// so the JSON stays minimal.
fn is_false(b: &bool) -> bool {
    !b
}

fn default_menu_bg_opacity() -> f32 {
    1.0
}
fn default_slice_highlight_opacity() -> f32 {
    1.0
}
fn default_center_label_size() -> f32 {
    13.0
}
fn default_tooltip_delay_ms() -> u32 {
    600
}
fn default_tooltip_font_size() -> f32 {
    11.0
}
fn default_tooltip_use_monospace() -> bool {
    true
}
fn default_tooltip_bg_color() -> String {
    "crust".to_string()
}
fn default_tooltip_bg_alpha() -> f32 {
    0.85
}
fn default_tooltip_text_color() -> String {
    "text".to_string()
}
fn default_aurora_intensity() -> f32 {
    0.6
}
fn default_ripple_intensity() -> f32 {
    0.7
}
fn default_hover_glow_intensity() -> f32 {
    0.6
}
fn default_dispatch_burst_intensity() -> f32 {
    0.7
}
fn default_dispatch_burst_style() -> DispatchBurstStyle {
    DispatchBurstStyle::Sparks
}
fn default_sdf_ring_intensity() -> f32 {
    0.0
}
fn default_hover_tilt_intensity() -> f32 {
    0.65
}
fn default_hover_tilt_shadow() -> f32 {
    0.5
}
fn default_hover_tilt_sharpness() -> f32 {
    0.5
}
fn default_disc_bevel_intensity() -> f32 {
    0.6
}
fn default_center_dome_intensity() -> f32 {
    0.6
}
fn default_slice_bevel_intensity() -> f32 {
    0.55
}
fn default_drop_shadow_intensity() -> f32 {
    0.55
}
fn default_specular_sweep_intensity() -> f32 {
    0.4
}
fn default_specular_sweep_period_s() -> f32 {
    8.0
}
fn default_light_angle_rad() -> f32 {
    // -3π/4 = upper-left in canvas convention (slice 0 at -π/2
    // = top). Universal "this is 3D" lighting convention.
    -std::f32::consts::FRAC_PI_2 - std::f32::consts::FRAC_PI_4
}
fn default_page_name_show() -> bool {
    true
}
fn default_page_name_visible_ms() -> u32 {
    1200
}
fn default_page_name_transition_ms() -> u32 {
    300
}
fn default_page_name_slide_distance_px() -> f32 {
    30.0
}
fn default_page_name_arced() -> bool {
    true
}
fn default_page_name_use_monospace() -> bool {
    true
}
impl Default for VisualSettings {
    fn default() -> Self {
        VisualSettings {
            menu_background_opacity: default_menu_bg_opacity(),
            slice_highlight_opacity: default_slice_highlight_opacity(),
            center_label_size: default_center_label_size(),
            font_family: String::new(),
            tooltip_delay_ms: default_tooltip_delay_ms(),
            tooltip_font_size: default_tooltip_font_size(),
            tooltip_use_monospace: default_tooltip_use_monospace(),
            tooltip_font_family: String::new(),
            tooltip_bg_color: default_tooltip_bg_color(),
            tooltip_bg_alpha: default_tooltip_bg_alpha(),
            tooltip_text_color: default_tooltip_text_color(),
            aurora_intensity: default_aurora_intensity(),
            ripple_intensity: default_ripple_intensity(),
            hover_glow_intensity: default_hover_glow_intensity(),
            dispatch_burst_intensity: default_dispatch_burst_intensity(),
            dispatch_burst_style: default_dispatch_burst_style(),
            sdf_ring_intensity: default_sdf_ring_intensity(),
            hover_tilt_intensity: default_hover_tilt_intensity(),
            hover_tilt_shadow: default_hover_tilt_shadow(),
            hover_tilt_sharpness: default_hover_tilt_sharpness(),
            disc_bevel_intensity: default_disc_bevel_intensity(),
            center_dome_intensity: default_center_dome_intensity(),
            slice_bevel_intensity: default_slice_bevel_intensity(),
            drop_shadow_intensity: default_drop_shadow_intensity(),
            specular_sweep_intensity: default_specular_sweep_intensity(),
            specular_sweep_period_s: default_specular_sweep_period_s(),
            light_angle_rad: default_light_angle_rad(),
            page_name_show: default_page_name_show(),
            page_name_visible_ms: default_page_name_visible_ms(),
            page_name_transition_ms: default_page_name_transition_ms(),
            page_name_slide_distance_px: default_page_name_slide_distance_px(),
            page_name_arced: default_page_name_arced(),
            page_name_use_monospace: default_page_name_use_monospace(),
            page_name_font_family: String::new(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct RadialMenuConfig {
    /// Legacy single-page slice list. Pre-multipage configs only
    /// have this. Loaders should call [`Self::normalize_pages`] —
    /// it lifts these into `pages[0]` and clears the field so
    /// downstream code only reads from `pages`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub slices: Vec<Slice>,

    /// Multi-page menu. Page 0 is the default page (always
    /// reachable via the scroll cycle). Additional pages are either
    /// extra global pages or app-context pages that auto-select on
    /// focus. After [`Self::normalize_pages`] runs, this is
    /// guaranteed to contain at least one page.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub pages: Vec<RadialPage>,

    /// Replaces the configured slot 5 (Emoji) with an Easy-Switch submenu
    /// when true. Mirrors the existing daemon behaviour.
    #[serde(default)]
    pub easy_switch_shortcuts: bool,

    /// OS labels for each Easy-Switch host slot (length 3). Used to pick
    /// the host icon in the Easy-Switch submenu.
    #[serde(default)]
    pub easy_switch_host_os: Vec<String>,

    /// Per-element animation tweaks. Optional — when missing, every
    /// element falls back to its `ElementAnimation::*_default()`
    /// preset. Inotify-reloaded so users iterate live.
    #[serde(default)]
    pub animation: AnimationConfig,

    /// Static visual knobs (background opacity, highlight intensity)
    /// the user controls directly from the settings UI.
    #[serde(default)]
    pub visuals: VisualSettings,
}

impl RadialMenuConfig {
    /// Migrate legacy `slices` (pre-multipage configs) into
    /// `pages[0]` and ensure at least one page exists. Idempotent;
    /// safe to call on already-migrated configs. Run after every
    /// load/parse so the rest of the codebase only has to read
    /// from `pages`.
    pub fn normalize_pages(&mut self) {
        if !self.slices.is_empty() {
            let legacy = std::mem::take(&mut self.slices);
            if self.pages.is_empty() {
                self.pages.push(RadialPage {
                    name: "Default".into(),
                    slices: legacy,
                    app_classes: Vec::new(),
                    include_in_scroll: true,
                    slot_count: default_slot_count(),
                });
            } else if self.pages[0].slices.is_empty() {
                // Tolerate a config that has both fields populated by
                // hand: prefer pages[0] if it has slices, otherwise
                // backfill from the legacy field.
                self.pages[0].slices = legacy;
            }
        }
        if self.pages.is_empty() {
            self.pages.push(RadialPage::default());
        }
    }

    /// Indices of the pages that participate in the scroll-wheel
    /// cycle. A global page (empty `app_classes`) is always in the
    /// cycle; an app-context page is in the cycle only when
    /// `include_in_scroll` is true.
    pub fn cycle_pages(&self) -> Vec<usize> {
        self.pages
            .iter()
            .enumerate()
            .filter(|(_, p)| p.app_classes.is_empty() || p.include_in_scroll)
            .map(|(i, _)| i)
            .collect()
    }

    /// Page index to activate when the menu opens with the given
    /// focused window class. First page whose `app_classes`
    /// contains the class (case-insensitive); falls back to 0.
    pub fn page_for_class(&self, class: Option<&str>) -> usize {
        let class = match class {
            Some(c) if !c.is_empty() => c,
            _ => return 0,
        };
        let lc = class.to_lowercase();
        self.pages
            .iter()
            .position(|p| p.app_classes.iter().any(|c| c.to_lowercase() == lc))
            .unwrap_or(0)
    }

    /// Read access to the slices of a specific page index, with
    /// graceful fallback to an empty slice if the index is out of
    /// range — guards against a stale active-page index after a
    /// page is deleted.
    pub fn slices_of(&self, page_idx: usize) -> &[Slice] {
        self.pages
            .get(page_idx)
            .map(|p| p.slices.as_slice())
            .unwrap_or(&[])
    }

    /// Convenience: slices of page 0 (the default page). Used by
    /// callers that don't yet support multi-page navigation —
    /// daemon HID++ button mapping, the dump_menu example, etc.
    pub fn default_slices(&self) -> &[Slice] {
        self.slices_of(0)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AppConfig {
    #[serde(default)]
    pub theme: ThemeName,

    #[serde(default)]
    pub radial_menu: RadialMenuConfig,

    /// Per-event haptic feedback patterns + debounce timings.
    /// Optional in the JSON; missing = sensible defaults from
    /// `HapticsConfig::default()`.
    #[serde(default)]
    pub haptics: HapticsConfig,

    /// Pointer speed + acceleration (Point & Scroll tab → Pointer).
    #[serde(default)]
    pub pointer: PointerConfig,

    /// Scroll wheel behaviour (Point & Scroll tab → Scroll).
    #[serde(default)]
    pub scroll: ScrollConfig,

    /// Per-button action assignments. Same on-disk shape as the
    /// daemon's `daemon::config::ButtonsConfig`.
    #[serde(default)]
    pub buttons: ButtonsConfig,

    /// Game-Mode block — currently the gamepad-rumble → haptic
    /// redirect knobs. See `oxidemx/HAPTIC_GAMEPAD_BRIDGE_DESIGN.md`.
    /// Optional; missing block deserialises to `GamingConfig::default()`
    /// which leaves every feature off.
    #[serde(default)]
    pub gaming: GamingConfig,

    /// Per-app menu profile names. When the focused window's WM_CLASS (or
    /// equivalent) matches a key here, the daemon points the overlay at
    /// `~/.config/oxidemx/profiles/<value>.json` instead of the main
    /// config. Empty by default — no profile switching.
    #[serde(default, skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    pub app_profiles: std::collections::BTreeMap<String, String>,

    /// Indicator-popup preferences (mode, quick toggles, sliders, etc.).
    /// Stored in the `popup` table of `config.json`; absent = defaults.
    #[serde(default)]
    pub popup: crate::popup::PopupConfig,

    /// Overlay-window preferences (AI chat size, agent knobs).
    /// Absent = defaults.
    #[serde(default)]
    pub overlay: OverlayConfig,
}

/// Overlay-window preferences persisted in the `overlay` table of
/// `config.json`.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct OverlayConfig {
    /// Persisted AI chat window size `(width, height)` in logical px,
    /// saved when the user releases the chat's resize grip. `None` =
    /// the legacy fixed 484×640. The overlay clamps to its minimum
    /// (420×560) on read so a hand-edited tiny value can't produce
    /// broken geometry.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chat_size: Option<(u32, u32)>,

    /// `(latitude, longitude)` for the Weather widget's Open-Meteo
    /// lookup. `None` = the weather wedge renders its stub.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub weather_location: Option<(f64, f64)>,

    /// Display name for the weather location ("Oslo, NO") — set by
    /// the settings geocoder alongside `weather_location`; shown in
    /// the wedge's hover popup header.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub weather_place: Option<String>,

    /// Temperature unit for the Weather widget. Fahrenheit is the
    /// default; `true` switches to Celsius (settings app toggle).
    #[serde(default)]
    pub weather_celsius: bool,

    /// AI agent knobs.
    #[serde(default)]
    pub ai: AiConfig,
}

/// AI agent configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiConfig {
    /// Command prefixes the `execute_command` agent tool may run
    /// without per-call confirmation. Matched against the leading
    /// tokens of the requested command (whole-token prefix match,
    /// not substring). Anything else requires an explicit user
    /// confirmation chip in the chat.
    #[serde(default = "default_command_allowlist")]
    pub command_allowlist: Vec<String>,
}

impl Default for AiConfig {
    fn default() -> Self {
        AiConfig {
            command_allowlist: default_command_allowlist(),
        }
    }
}

fn default_command_allowlist() -> Vec<String> {
    ["brightnessctl", "wpctl", "systemctl --user"]
        .map(String::from)
        .to_vec()
}

/// Default location of the user's main config: `~/.config/oxidemx/config.json`.
pub fn default_config_path() -> Option<PathBuf> {
    dirs_config_dir().map(|d| d.join("oxidemx").join("config.json"))
}

/// Bundled starter config — written to `~/.config/oxidemx/config.json`
/// the first time the overlay can't find one. Gives users a working
/// 8-slice menu on first run instead of an empty ring; they edit
/// from there in the settings UI (or by hand). Stored as raw JSON so
/// the file's schema is the single source of truth — no duplicated
/// Rust struct literal that would drift from the on-disk version.
pub const DEFAULT_CONFIG_JSON: &str = include_str!("../default-config.json");

/// Write the bundled starter config to `path` if no file exists
/// there yet. Returns `true` if the file was created (a fresh
/// seed), `false` if it already existed.
pub fn seed_default_config_if_missing(path: &Path) -> Result<bool, ConfigError> {
    if path.exists() {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(ConfigError::Io)?;
    }
    std::fs::write(path, DEFAULT_CONFIG_JSON).map_err(ConfigError::Io)?;
    Ok(true)
}

/// Directory holding per-app profile overrides (one JSON file per profile).
pub fn profiles_dir() -> Option<PathBuf> {
    dirs_config_dir().map(|d| d.join("oxidemx").join("profiles"))
}

fn dirs_config_dir() -> Option<PathBuf> {
    // Avoid pulling in `dirs` at this level — keep oxidemx-shared
    // dependency-free aside from serde so the daemon can use it without
    // adding any indirect deps. Mirror dirs::config_dir()'s logic.
    if let Some(xdg) = std::env::var_os("XDG_CONFIG_HOME") {
        let p = PathBuf::from(xdg);
        if p.is_absolute() {
            return Some(p);
        }
    }
    std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config"))
}

impl AppConfig {
    /// Load and parse a config file from disk. Returns the default config
    /// if the file is missing — the daemon writes a fresh one on first
    /// run.
    pub fn load_from(path: &Path) -> Result<Self, ConfigError> {
        let mut cfg = match std::fs::read_to_string(path) {
            Ok(s) => serde_json::from_str::<Self>(&s).map_err(ConfigError::Parse)?,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                let mut def = AppConfig::default();
                def.radial_menu.normalize_pages();
                return Ok(def);
            }
            Err(e) => return Err(ConfigError::Io(e)),
        };
        cfg.radial_menu.normalize_pages();
        Ok(cfg)
    }
}

#[derive(Debug)]
pub enum ConfigError {
    Io(std::io::Error),
    Parse(serde_json::Error),
}

impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConfigError::Io(e) => write!(f, "config I/O error: {e}"),
            ConfigError::Parse(e) => write!(f, "config parse error: {e}"),
        }
    }
}

impl std::error::Error for ConfigError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ConfigError::Io(e) => Some(e),
            ConfigError::Parse(e) => Some(e),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_minimal_config() {
        let json = r#"{
            "theme": "dracula",
            "radial_menu": {
                "slices": [
                    {"label": "Terminal", "type": "exec", "command": "ptyxis", "color": "green", "icon": "utilities-terminal-symbolic"}
                ]
            }
        }"#;
        let mut cfg: AppConfig = serde_json::from_str(json).unwrap();
        cfg.radial_menu.normalize_pages();
        assert_eq!(cfg.theme, ThemeName::Dracula);
        // Legacy slices migrated into pages[0].
        assert!(cfg.radial_menu.slices.is_empty());
        assert_eq!(cfg.radial_menu.pages.len(), 1);
        let page = &cfg.radial_menu.pages[0];
        assert_eq!(page.slices.len(), 1);
        let s = &page.slices[0];
        assert_eq!(s.label, "Terminal");
        assert_eq!(s.kind, ActionKind::Exec);
        assert_eq!(s.command, "ptyxis");
    }

    #[test]
    fn normalize_pages_is_idempotent() {
        let json = r#"{
            "radial_menu": {
                "pages": [
                    {"name": "Main", "slices": [
                        {"label": "A", "type": "exec", "command": "true"}
                    ]},
                    {"name": "Dev", "app_classes": ["code"], "include_in_scroll": false,
                     "slices": [{"label": "B", "type": "exec", "command": "true"}]}
                ]
            }
        }"#;
        let mut cfg: AppConfig = serde_json::from_str(json).unwrap();
        cfg.radial_menu.normalize_pages();
        cfg.radial_menu.normalize_pages();
        assert_eq!(cfg.radial_menu.pages.len(), 2);
        assert_eq!(cfg.radial_menu.cycle_pages(), vec![0]);
        assert_eq!(cfg.radial_menu.page_for_class(Some("code")), 1);
        assert_eq!(cfg.radial_menu.page_for_class(Some("Code")), 1);
        assert_eq!(cfg.radial_menu.page_for_class(Some("firefox")), 0);
        assert_eq!(cfg.radial_menu.page_for_class(None), 0);
    }

    #[test]
    fn default_config_round_trips_losslessly() {
        // The bundled starter config must survive a parse → serialize →
        // parse cycle without dropping slices/pages or inventing
        // widget/dial keys on plain slices.
        let mut cfg: AppConfig = serde_json::from_str(DEFAULT_CONFIG_JSON).unwrap();
        cfg.radial_menu.normalize_pages();
        let json = serde_json::to_string(&cfg).unwrap();
        let mut back: AppConfig = serde_json::from_str(&json).unwrap();
        back.radial_menu.normalize_pages();
        assert_eq!(cfg.radial_menu.pages.len(), back.radial_menu.pages.len());
        for (a, b) in cfg
            .radial_menu
            .pages
            .iter()
            .zip(back.radial_menu.pages.iter())
        {
            assert_eq!(a.name, b.name);
            assert_eq!(a.slices.len(), b.slices.len());
            for (sa, sb) in a.slices.iter().zip(b.slices.iter()) {
                assert_eq!(sa.label, sb.label);
                assert_eq!(sa.kind, sb.kind);
                assert_eq!(sa.command, sb.command);
            }
        }
        // Plain slices must not gain widget/dial keys on disk —
        // check the Apps page (the new Device/Widgets pages carry
        // them legitimately).
        let apps = serde_json::to_string(&cfg.radial_menu.pages[0]).unwrap();
        assert!(!apps.contains("\"widget\""), "widget key leaked: {apps}");
        assert!(!apps.contains("\"dial\""), "dial key leaked: {apps}");
        // And the new built-in pages parsed into typed bindings.
        let device = cfg
            .radial_menu
            .pages
            .iter()
            .find(|p| p.name == "Device")
            .expect("Device page shipped in defaults");
        assert!(device
            .slices
            .iter()
            .any(|s| s.dial == Some(DialKind::Brightness)));
        let widgets = cfg
            .radial_menu
            .pages
            .iter()
            .find(|p| p.name == "Widgets")
            .expect("Widgets page shipped in defaults");
        assert!(widgets
            .slices
            .iter()
            .any(|s| s.widget.as_ref().map(|w| w.source) == Some(WidgetSource::Cpu)));
    }

    #[test]
    fn widget_and_dial_slices_round_trip() {
        let json = r#"{
            "radial_menu": { "pages": [ { "name": "Widgets", "slices": [
                {"label": "CPU", "type": "widget", "color": "teal",
                 "widget": {"source": "cpu"}},
                {"label": "Net", "type": "widget", "color": "blue",
                 "widget": {"source": "network", "format": "{} Mb/s"}},
                {"label": "Brightness", "type": "dial", "color": "yellow",
                 "dial": "brightness"}
            ] } ] }
        }"#;
        let cfg: AppConfig = serde_json::from_str(json).unwrap();
        let s = &cfg.radial_menu.pages[0].slices;
        assert_eq!(s[0].kind, ActionKind::Widget);
        assert_eq!(s[0].widget.as_ref().unwrap().source, WidgetSource::Cpu);
        assert_eq!(s[0].widget.as_ref().unwrap().format, None);
        assert_eq!(s[1].widget.as_ref().unwrap().source, WidgetSource::Network);
        assert_eq!(
            s[1].widget.as_ref().unwrap().format.as_deref(),
            Some("{} Mb/s")
        );
        assert_eq!(s[2].kind, ActionKind::Dial);
        assert_eq!(s[2].dial, Some(DialKind::Brightness));
        let back = serde_json::to_string(&cfg).unwrap();
        assert!(back.contains(r#""source":"cpu""#));
        assert!(back.contains(r#""dial":"brightness""#));
    }

    #[test]
    fn overlay_section_defaults_and_round_trips() {
        // Absent section → defaults (legacy size, stock allowlist).
        let cfg: AppConfig = serde_json::from_str("{}").unwrap();
        assert_eq!(cfg.overlay.chat_size, None);
        assert_eq!(
            cfg.overlay.ai.command_allowlist,
            vec!["brightnessctl", "wpctl", "systemctl --user"]
        );
        // Populated section survives the round trip.
        let json = r#"{"overlay": {"chat_size": [560, 720],
                       "ai": {"command_allowlist": ["echo"]}}}"#;
        let cfg: AppConfig = serde_json::from_str(json).unwrap();
        assert_eq!(cfg.overlay.chat_size, Some((560, 720)));
        assert_eq!(cfg.overlay.ai.command_allowlist, vec!["echo"]);
        let back = serde_json::to_string(&cfg).unwrap();
        assert!(back.contains(r#""chat_size":[560,720]"#));
    }

    #[test]
    fn unknown_theme_round_trips_as_custom() {
        let cfg: AppConfig = serde_json::from_str(r#"{"theme":"my-cool-theme"}"#).unwrap();
        assert_eq!(cfg.theme, ThemeName::Custom("my-cool-theme".into()));
        let back = serde_json::to_string(&cfg).unwrap();
        assert!(back.contains(r#""theme":"my-cool-theme""#));
    }
}
